# Generated by Django 4.0.3 on 2022-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=80)),
                ('donor_c', models.CharField(max_length=11)),
                ('donor_email', models.EmailField(max_length=80)),
                ('donor_address', models.TextField(blank=True)),
                ('amount', models.PositiveIntegerField()),
                ('designation', models.CharField(choices=[('FTC', 'Feed the Children'), ('FFTH', 'Food for the Hungry'), ('WFP', 'World Food Programme'), ('AAH', 'Action Against Hunger'), ('RAHP', 'Rise Against Hunger Philippines'), ('O', 'Others')], max_length=80, null=True)),
                ('service', models.CharField(choices=[('GP', 'GrabPay'), ('GC', 'Gcash'), ('PMY', 'Paymaya')], max_length=80, null=True)),
                ('eWallet', models.PositiveIntegerField()),
                ('dMessage', models.TextField(max_length=200)),
            ],
        ),
    ]
