# Generated by Django 4.0.3 on 2022-07-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtvsn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='dMessage',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='eWallet',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='service',
        ),
    ]
