# Generated by Django 4.0.3 on 2022-07-06 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtvsn', '0002_remove_donate_amount_remove_donate_dmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donator_comment', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('donation_designation', models.CharField(choices=[('FTC', 'Feed the Children'), ('FFTH', 'Food for the Hungry'), ('WFP', 'World Food Programme'), ('AAH', 'Action Against Hunger'), ('RAHP', 'Rise Against Hunger Philippines'), ('O', 'Others')], max_length=100, null=True)),
                ('donation_amount', models.CharField(max_length=99999)),
                ('payment_services', models.CharField(choices=[('GP', 'GrabPay'), ('GC', 'Gcash'), ('PMY', 'Paymaya')], max_length=100, null=True)),
                ('eWallet_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=80)),
                ('contact_no', models.CharField(max_length=11)),
                ('donor_email', models.EmailField(max_length=80)),
                ('donor_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Donate',
        ),
        migrations.AddField(
            model_name='donation',
            name='name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtvsn.donor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtvsn.donor'),
        ),
    ]
