# Generated by Django 4.0.3 on 2022-07-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtvsn', '0003_comment_donation_donor_delete_donate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='donor',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='name_id',
            new_name='donor_id',
        ),
    ]
