# Generated by Django 4.0.3 on 2022-07-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtvsn', '0004_rename_name_comment_donor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donor_id',
            new_name='donor',
        ),
    ]
