# Generated by Django 4.0.3 on 2022-07-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtvsn', '0005_rename_donor_id_donation_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_services',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
